In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [4]:
import zipfile

zip_path = "/content/drive/MyDrive/MultilingualFakeNews/data/TALLIP-FakeNews-Dataset.zip"

extract_path = "/content/TALLIP"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted.")

Dataset extracted.

In [5]:
#Load first dataset
import pandas as pd

file_path = "/content/TALLIP/TALLIP-FakeNews-Dataset/English/Train/train_English_Data_Complete_FakeNews.txt"

df = pd.read_csv(
    file_path,
    sep="\t"
)

df.head()

,Domain,Topic,News,Label
0,Sports,Roger Federer beats Frances Tiafoe on return ...,Roger Federer beat American teenager Frances T...,Legit
1,Celebrity,'It was a long time coming': Heidi Klum ends s...,Seal and Heidi Klum insisted their split was '...,Fake
2,Celebrity,Liam Payne Just Dissed Harry Styles' Solo Music,"Harry Styles' new music isn't for everyone, no...",Fake
3,Entertainment,We all know why the right is angry at Tomi Lahren,Conservative darling-turned-pariah Tomi Lahren...,Legit
4,Celebrity,Inside Beyoncé's baby shower,Don't act like you didn't know Beyoncé was goi...,Legit

In [6]:
#Check dataset size
print(df.shape)

(588, 4)

In [7]:
#Check labels
df["Label"].value_counts()

Label
Legit    298
Fake     290
Name: count, dtype: int64

In [8]:
#Checking for missing values
df.isnull().sum()

Domain     0
Topic     10
News       0
Label      0
dtype: int64

In [9]:
# Checking the domains
df["Domain"].value_counts()

Domain
Celebrity        305
Business          55
Politics          50
Education         49
Entertainment     47
Sports            43
Technology        39
Name: count, dtype: int64

In [10]:
df.shape
df["Label"].value_counts()
df.isnull().sum()

Domain     0
Topic     10
News       0
Label      0
dtype: int64

In [11]:
# Create a clean dataset
df = df.dropna(subset=["News", "Label"])

print(df.shape)

(588, 4)

In [12]:
# Inspect label distribution
df["Label"].value_counts()

Label
Legit    298
Fake     290
Name: count, dtype: int64

In [13]:
#Inspect domain distribution
df["Domain"].value_counts()

Domain
Celebrity        305
Business          55
Politics          50
Education         49
Entertainment     47
Sports            43
Technology        39
Name: count, dtype: int64

In [14]:
# Creating the training text column
df["Topic"] = df["Topic"].fillna("")

df["text"] = (
    df["Topic"].astype(str)
    + " "
    + df["News"].astype(str)
)

In [15]:
df[["text", "Label"]].head()

                                                text  Label
0   Roger Federer beats Frances Tiafoe on return ...  Legit
1  'It was a long time coming': Heidi Klum ends s...   Fake
2  Liam Payne Just Dissed Harry Styles' Solo Musi...   Fake
3  We all know why the right is angry at Tomi Lah...  Legit
4  Inside Beyoncé's baby shower Don't act like yo...  Legit

In [16]:
# Convert labels to numbers
label_map = {
    "Fake": 1,
    "Legit": 0
}

df["target"] = df["Label"].map(label_map)

df[["Label", "target"]].head()

   Label  target
0  Legit       0
1   Fake       1
2   Fake       1
3  Legit       0
4  Legit       0

In [17]:
# Saving the clean dataset
df[["text", "target"]].to_csv(
    "/content/drive/MyDrive/MultilingualFakeNews/data/english_clean.csv",
    index=False
)

In [18]:
# Confirmations
df["Label"].value_counts()

Label
Legit    298
Fake     290
Name: count, dtype: int64

In [19]:
df["Domain"].value_counts()

Domain
Celebrity        305
Business          55
Politics          50
Education         49
Entertainment     47
Sports            43
Technology        39
Name: count, dtype: int64